# https://computingforgeeks.com/monitor-apache-kafka-with-prometheus-and-grafana/
# https://computingforgeeks.com/how-to-install-prometheus-on-rhel-8/

- name: Download
  ansible.builtin.shell:
    cmd: wget https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.13.0/jmx_prometheus_javaagent-0.13.0.jar

# todo variables for dirs
- name: Ensures  dir exists
  file: path=/etc/kafka/exporter state=directory

# todo variables for dirs
- name: Copy to install folders
  ansible.builtin.shell:
    cmd: cp ./jmx_prometheus_javaagent-0.13.0.jar /etc/kafka/exporter/jmx_prometheus_javaagent-0.13.0.jar

- name: set configuration
  template: src=templates/config.yml.j2 dest=/etc/kafka/exporter/config.yml force=yes

# TODO Add startup to service
# Environment="KAFKA_OPTS=-javaagent:/usr/local/kafka-server/libs/jmx_prometheus_javaagent-0.13.0.jar=7075:/usr/local/kafka-server/config/sample_jmx_exporter.yml"
# also add specified port to firewall    
# more info heer https://github.com/prometheus/jmx_exporter

