# https://computingforgeeks.com/how-to-install-prometheus-on-rhel-8/
- name: Create a data directory 
  ansible.builtin.file:
    path: /var/lib/prometheus # data
    state: directory
    mode: 0775

- name: create prometheus directories
  file:
    path: "/etc/prometheus/{{ item }}/"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - rules 
    - rules.d
    - files_sd

- name: Create an install directory
  ansible.builtin.file:
    path: /usr/local/bin/prometheus # data
    state: directory
    mode: 0775

- name: Download
  ansible.builtin.shell:
    cmd: wget https://github.com/prometheus/prometheus/releases/download/v2.34.0/prometheus-2.34.0.linux-amd64.tar.gz
    
- name: Untar
  ansible.builtin.shell:
    cmd: tar xvf prometheus-*.tar.gz

- name: Change to folder
  ansible.builtin.shell:
    cmd: cd prometheus-2.34.0.linux-amd64

- name: Copy to install folders
  ansible.builtin.shell:
    cmd: sudo cp prometheus promtool /usr/local/bin/


- name: Copy to instakll folders
  ansible.builtin.shell:
    cmd: sudo cp -r prometheus.yml consoles/ console_libraries/ /etc/prometheus/

- name: set configuration
  template: src=templates/prometheus.yml.j2 dest=/etc/prometheus/prometheus.yml force=yes


    


