- name: start kafka
  command: sudo systemctl start kafka

- name: stop kafka
  command: sudo systemctl stop kafka

- name: status kafka
  command: sudo systemctl status kafka

- name: enable kafka
  command: sudo systemctl enable kafka


- name: reload daemon
  command: sudo systemctl daemon-reload

